global_costmap:
  global_frame: odom
  robot_base_frame: chassis
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  static_map: true
  rolling_window: false
  resolution: 0.1
  transform_tolerance: 1.0
  map_type: costmap
